### ISSUE TITLE
email to dev@codiad.com regarding drag&drop plugin

### ISSUE THREAD

**Issue by daeks** [Andr3as/Codiad-DragDrop#1]
First, thanks for a great editor. Very polished and easy to use. I was wondering if there was any way to extend the drag and drop plugin to allow the html contents of one file to be dragged into another. I'd use a lot of re-usable snippets and it would be great to keep a series of files in a folder (each file would be a block of code) and when needed, drag that file over into the active tab to add that content right to the active file. Thoughts?

Again, great job here and thanks!

Shawn

**Comment by Andr3as** [comment]
Dragging it directly to the code wasn't possible, I had to find another solution. I implemented it with 26f900b1f2.

Just enable the feature in the settings.

![screen](https://cloud.githubusercontent.com/assets/4389878/7186316/0cff9f7a-e469-11e4-81f8-6c465752df7f.png)
